home/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from home import views
from order import views as orderviews

urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),


    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contactus, name='contactus'),
    path('category/<int:id>/<slug:slug>/', views.category_product, name='category_product'),
    path('search/', views.search, name='search_product'),
    path('product/<int:id>/<slug:slug>', views.product_details, name='product_details'),
    path('order/', orderviews.shopcart, name='shopcart' ),
    path('faq/', views.faq, name='faq')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path, include
from . import views
#from product import views

app_name='Product'

urlpatterns = [
    path('', views.index, name='index'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('comment/<int:id>/', views.comment, name='comment'),
]

home/models.py
from django.db import models
from django import forms
from ckeditor_uploader.fields import RichTextUploadingField
from product.models import Product


# Create your models here.
class Setting(models.Model):
    STATUS =(
        ('True', 'True'),
        ('False','False'),
    )
    Title = models.CharField(max_length=150)
    Keywords = models.CharField(max_length=255)
    Description = models.CharField(max_length=255)
    Company = models.CharField(max_length=50)
    Address = models.CharField(blank=True, max_length=100)
    Phone = models.CharField(blank=True, max_length=15)
    Fax = models.CharField(blank=True, max_length=100)
    Email = models.CharField(blank=True, max_length=50)
    Smtpserver = models.CharField(blank=True, max_length=50)
    Smtpmail = models.CharField(blank=True,max_length=50)
    Smtpport = models.CharField(blank=True,max_length=15)
    Icon = models.ImageField(blank=True,upload_to='images/')
    Facebook = models.CharField(blank=True, max_length=100)
    Instagram = models.CharField(blank=True,max_length=100)
    Twitter = models.CharField(blank=True,max_length=100)
    Youtube = models.CharField(blank=True,max_length=100)
    Aboutus = RichTextUploadingField(blank=True)
    Contact = RichTextUploadingField(blank=True)
    References = RichTextUploadingField(blank=True)
    Status = models.CharField(max_length=50, choices=STATUS)
    Create_at = models.DateTimeField(auto_now_add=True)
    Update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.Title

class ContactMessage(models.Model):
    STATUS =(
        ('New','New'),
        ('Read','Read'),
        ('Closed','Closed'),
    )
    Name = models.CharField(blank=True,max_length=100)
    Email = models.CharField(blank=True,max_length=100)
    Subject = models.CharField(blank=True,max_length=255)
    Message = models.CharField(blank=True,max_length=255)
    Note = models.CharField(blank=True,max_length=255)
    Status = models.CharField(blank=True,choices=STATUS,default='New',max_length=100)
    IP = models.CharField(blank=True,max_length=255)
    Create_at = models.DateTimeField(auto_now_add=True)
    Update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.Name

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['Name','Email','Subject','Message']
        widgets = {
            'Name' : forms.TextInput(attrs={'class':'input','placeholder':'Name'}),
            'Email': forms.TextInput(attrs={'class':'input','placeholder':'Email'}),
            'Subject': forms.TextInput(attrs={'class':'input','placeholder':'Subject'}),
            'Message': forms.Textarea(attrs={'class':'input','placeholder':'Message'}),
        }

class FAQ(models.Model):
    STATUS =(
    ('T','True'),
    ('F','False'),
    )
    Ordernumber = models.IntegerField()
    Question = models.CharField(max_length=200)
    Answer = RichTextUploadingField()
    Status = models.CharField(max_length=10,choices=STATUS)
    Create_at = models.DateTimeField(auto_now_add=True)
    Update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.Question

home/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)
    catid = forms.IntegerField()

home/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.contrib import messages
from . import models
from home.models import ContactMessage, ContactForm
from product.models import Category, Product, Images, Comments
from order.models import ShopCart
from home.forms import SearchForm
from django.db.models import Avg, Max, Min, Sum, Count
import json


# Create your views here.
def index(request):
    setting = models.Setting.objects.get(pk=1)
    category = Category.objects.all()
    products_slider = Product.objects.all().order_by('id')[:4]
    products_latest = Product.objects.all().order_by('-id')[:4]
    products_picked = Product.objects.all().order_by('?')[:4]
    page = 'home'
    current_user = request.user
    orderqty = ShopCart.objects.filter(User_id=current_user.id).aggregate(Sum('Quantity'))
    orderqty = orderqty["Quantity__sum"]
    shopcart = ShopCart.objects.filter(User_id=current_user.id)

    total = 0
    for sctotal in shopcart:
        total += sctotal.Quantity * sctotal.Product.Price

    context = {
        'setting':setting,
        'page':page,
        'category':category,
        'products_slider':products_slider,
        'products_latest':products_latest,
        'products_picked':products_picked,
        'orderqty':orderqty,
        'shopcart':shopcart,
        'total':total,
    }
    return render(request, 'index.html', context)

def aboutus(request):
    category = Category.objects.all()
    setting = models.Setting.objects.get(pk=1)
    context={
        'setting':setting,
        'category':category,
        }
    return render(request, 'about.html', context )

def contactus(request):
    category = Category.objects.all()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        #print(form)
        if form.is_valid():
            data = ContactMessage() #Its a model and Just for data checking with model field. If it does not check then also data will save
            data.Name = form.cleaned_data['Name']
            data.Email = form.cleaned_data['Email']
            data.Subject = form.cleaned_data['Subject']
            data.Message = form.cleaned_data['Message']
            data.ip = request.META.get('REMOTE_ADDR')
            #print(data.ip)
            #print(data.Message)
            data.save()
            messages.success(request,'Thanks for your message')
            #form.save() # Direct ata dileo hobe
            return HttpResponseRedirect('/contact')

    setting = models.Setting.objects.get(pk=1)
    form = models.ContactForm()

    current_user = request.user
    orderqty = ShopCart.objects.filter(User_id=current_user.id).aggregate(Sum('Quantity'))
    orderqty = orderqty["Quantity__sum"]
    shopcart = ShopCart.objects.filter(User_id=current_user.id)

    total = 0
    for sctotal in shopcart:
        total += sctotal.Quantity * sctotal.Product.Price

    context={
        'setting':setting,
        'form':form,
        'category':category,
        'orderqty':orderqty,
        'shopcart':shopcart,
        'total':total,
        }
    return render(request, 'contact.html', context)

def category_product(request,id,slug):
    setting = models.Setting.objects.get(pk=1)
    category = Category.objects.all()
    products = Product.objects.filter(Category_id=id)
    context = {
        'setting':setting,
        'category':category,
        'product':products,
        }
    return render(request, 'category_product.html', context)


def search(request):
    setting = models.Setting.objects.get(pk=1)
    if request.method=="POST":
        category = Category.objects.all()
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            print(query)
            catid = form.cleaned_data['catid']
            if catid==0:
                products = Product.objects.filter(Title__icontains=query)
            else:
                products = Product.objects.filter(Title__icontains=query,Category_id=catid)

        current_user = request.user
        orderqty = ShopCart.objects.filter(User_id=current_user.id).aggregate(Sum('Quantity'))
        orderqty = orderqty["Quantity__sum"]
        shopcart = ShopCart.objects.filter(User_id=current_user.id)

        total = 0
        for sctotal in shopcart:
            total += sctotal.Quantity * sctotal.Product.Price
            context ={
                'setting':setting,
                'category':category,
                'products':products,
                'query':query,
                'orderqty':orderqty,
                'shopcart':shopcart,
                'total':total,
            }
            return render(request, 'search_product.html', context)
    return HttpResponseRedirect('/')

def product_details(request,id,slug):
    category = Category.objects.all()
    product = Product.objects.get(pk=id)
    images = Images.objects.filter(Product_id=id)
    comments = Comments.objects.filter(Product_id=id)
    commentscount = Comments.objects.filter(Product_id=id).count()
    current_user = request.user
    orderqty = ShopCart.objects.filter(User_id=current_user.id).aggregate(Sum('Quantity'))
    orderqty = orderqty["Quantity__sum"]
    shopcart = ShopCart.objects.filter(User_id=current_user.id)

    total = 0
    for sctotal in shopcart:
        total += sctotal.Quantity * sctotal.Product.Price

    context = {
        'category':category,
        'product':product,
        'images':images,
        'comments':comments,
        'cc':commentscount,
        'orderqty':orderqty,
        'shopcart':shopcart,
        'total':total,
    }
    return render(request, 'product_details.html', context)

def faq(request):
    setting = models.Setting.objects.get(pk=1)
    category = Category.objects.all()
    faq = models.FAQ.objects.filter(Status="T").order_by("Ordernumber")
    context={
        'setting':setting,
        'category':category,
        'faq': faq,
    }
    return render(request, 'faq.html', context)

home/templates/about.html
{% extends 'homebase.html' %}
{% block title %} {{ setting.Title }} {% endblock %}
{% block description %} {{ setting.keywords }} {% endblock %}
{% block keywords %} {{ setting.Description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="">Home</a></li>
      <li class="active">About</li>
    </ul>
  </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">{{ setting.Aboutus|safe }}</div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /section -->

 {% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

home/templates/contact.html
{% extends 'homebase.html' %}
{% block title %} {{ setting.Title }} {% endblock %}
{% block description %} {{ setting.keywords }} {% endblock %}
{% block keywords %} {{ setting.Description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="">Home</a></li>
      <li class="active">Contact</li>
    </ul>
  </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
        <div class="col-md-4">
          <form id="checkout-form" class="clearfix" method="POST">
            {% csrf_token %}
          <div class="billing-details">
            <div class="section-title">
              <h3 class="title">Contact Form</h3>
              {% if messages %}
              {% for message in messages %}
              <div class=" alert alert-success">
                {{ message }}
              </div>
              {% endfor %}
              {% endif %}
            </div>
            {{ form.as_p }}
            <div class="form-group">
              <input class="primary-btn" type="submit" name="tel" placeholder="Submit">
            </div>
          </div>
          </form>
          </div>

        <div class="col-md-8">
          <div class="shiping-methods">
            <div class="section-title">{{ setting.Contact|safe }}</div>
          </div>
        </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /section -->

 {% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

home/templates/faq.html
{% extends 'homebase.html' %}
{% block title %} {{ setting.Title }} {% endblock %}
{% block description %} {{ setting.keywords }} {% endblock %}
{% block keywords %} {{ setting.Description }} {% endblock %}
{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block head %}
<script>
$( function() {
  $( "#accordion" ).accordion();
} );
</script>
{% endblock %}
{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="">Home</a></li>
      <li class="active">FAQ</li>
    </ul>
  </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
  <!-- container -->
  <div class="container">


<div id="accordion">
    {% for i in faq%}
  <h3>{{i.Question}}</h3>
  <div>
    <p>
  {{i.Answer|safe}}
    </p>
  </div>
  {% endfor %}
  </div>

  </div>
  <!-- /container -->
</div>
<!-- /section -->

 {% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

home/templates/header.html
{% load static %}
<!-- HEADER -->
<header>
   <!-- top Header -->
   <div id="top-header">
      <div class="container">
         <div class="pull-left">
            <span>Welcome to E-shop!</span>
            {% if messages %}
            {% for message in messages %}
            <div class=" alert alert-success">
               {{ message|safe }}
            </div>
            {% endfor %}
            {% endif %}
         </div>
         <div class="pull-right">
            <ul class="header-top-links">
               <li><a href="#">Store</a></li>
               <li><a href="#">Newsletter</a></li>
               <li><a href="/faq">FAQ</a></li>
               <li class="dropdown default-dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">ENG <i class="fa fa-caret-down"></i></a>
                  <ul class="custom-menu">
                     <li><a href="#">English (ENG)</a></li>
                     <li><a href="#">Russian (Ru)</a></li>
                     <li><a href="#">French (FR)</a></li>
                     <li><a href="#">Spanish (Es)</a></li>
                  </ul>
               </li>
               <li class="dropdown default-dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">USD <i class="fa fa-caret-down"></i></a>
                  <ul class="custom-menu">
                     <li><a href="#">USD ($)</a></li>
                     <li><a href="#">EUR (€)</a></li>
                  </ul>
               </li>
            </ul>
         </div>
      </div>
   </div>
   <!-- /top Header -->
   <!-- header -->
   <div id="header">
      <div class="container">
         <div class="pull-left">
            <!-- Logo -->
            <div class="header-logo">
               <a class="logo" href="#">
               <img src="{% static '' %}img/logo.png" alt="">
               </a>
            </div>
            <!-- /Logo -->
            <!-- Search -->
            <div class="header-search">
               <form action="/search/" method="POST">
                  {% csrf_token %}
                  <input id="query" name="query" class="input search-input" style="width:400px" type="text" placeholder="Enter your keyword">
                  <select name="catid" class="input search-categories">
                     <option value="0">All Categories</option>
                     {% load mptt_tags %}
                     {% recursetree category %}
                     {% if node.is_leaf_node %}
                     <option value="{{ node.id }}">{{ node.Title }}</option>
                     {% endif %}
                     {% if not node.is_leaf_node %}
                     <optgroup label="{{ node.Title }}">
                        {{ children }}
                     </optgroup>
                     {% endif %}
                     {% endrecursetree %}
                  </select>
                  <button class="search-btn"><i class="fa fa-search"></i></button>
               </form>
            </div>
            <!-- /Search -->
         </div>
         <div class="pull-right">
            <ul class="header-btns">
               <!-- Account -->
               <li class="header-account dropdown default-dropdown">
                  {% if user.id is not None %}
                  <div class="dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="true">
                     <div class="header-btns-icon">
                        <img src="{{request.session.userimage}}" style="height:40px; width:40px; border-radius:0px" alt="">
                     </div>
                     <strong class="text-uppercase">{{user.username}} <i class="fa fa-caret-down"></i></strong>
                  </div>
                  {% else %}
                  <a href="/user/login" class="text-uppercase">Login</a> / <a href="/user/signup" class="text-uppercase">Sing Up</a>
                  {% endif %}
                  <ul class="custom-menu">
                     <li><a href="/user/userprofile/"><i class="fa fa-user-o"></i> My Account</a></li>
                     <li><a href="#"><i class="fa fa-heart-o"></i> My Wishlist</a></li>
                     <li><a href="#"><i class="fa fa-exchange"></i> Compare</a></li>
                     <li><a href="#"><i class="fa fa-check"></i> Checkout</a></li>
                     <li><a href="/user/logout/"><i class="fa fa-unlock-alt"></i> Logout</a></li>
                  </ul>
               </li>
               <!-- /Account -->
               <!-- Cart -->
               <li class="header-cart dropdown default-dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                     <div class="header-btns-icon">
                        <i class="fa fa-shopping-cart"></i>
                        {% if orderqty is not None %}
                          <span class="qty"> {{ orderqty }}</span>
                        {% endif %}
                     </div>
                     <strong class="text-uppercase">My Cart:</strong>
                     <br>
                     <span>${{total}}</span>
                  </a>
                  <div class="custom-menu">
                     <div id="shopping-cart">
                        <div class="shopping-cart-list">
                           {% for sc in shopcart %}
                           <div class="product product-widget">
                              <div class="product-thumb">
                                 <img src="{{sc.Product.Image.url}}" alt="">
                              </div>
                              <div class="product-body">
                                 <h3 class="product-price">${{sc.Product.Price}} <span class="qty">x{{sc.Quantity}}</span></h3>
                                 <h2 class="product-name"><a href="/product/{{sc.Product_id}}/{{sc.Product.Slug}}">{{sc.Product.Title}}</a></h2>
                              </div>
                              <a href="/order/deleteformshopcart/{{sc.id}}"><button class="cancel-btn"><i class="fa fa-trash"></i></button></a>
                           </div>
                           {% endfor %}
                        </div>
                        <div class="shopping-cart-btns">
                           <button class="main-btn"><a href="/order">View Cart</a></button>
                           <button class="primary-btn">Checkout <i class="fa fa-arrow-circle-right"></i></button>
                        </div>
                     </div>
                  </div>
               </li>
               <!-- /Cart -->
               <!-- Mobile nav toggle-->
               <li class="nav-toggle">
                  <button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
               </li>
               <!-- / Mobile nav toggle -->
            </ul>
         </div>
      </div>
      <!-- header -->
   </div>
   <!-- container -->
</header>
<!-- /HEADER -->
<!--Start Auto Complete Search -->
<script>
   $( function() {
     $("#query").autocomplete({
       source: "{% url 'Product:search_auto' %}"
     });
   } );
</script>
<!--End Auto Complete Search -->

home/templates/index.html
{% extends 'homebase.html' %}
{% block title %} {{ setting.Title }} {% endblock %}
{% block description %} {{ setting.keywords }} {% endblock %}
{% block keywords %} {{ setting.Description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block slider %} {% include 'slider.html' %} {% endblock %}
{% block body %} {% include 'content.html' %} {% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

home/templates/product_details.html
{% extends 'homebase.html' %}
{% block title %} {{ product.Title }} {% endblock %}
{% block description %} {{ product.keywords }} {% endblock %}
{% block keywords %} {{ product.Description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li><a href="/category/{{product.Category_id}}/{{product.Category.Slug}}">{{ product.Category.Title}}</a></li>
      <li class="active">{{product.Title}}</li>
    </ul>
  </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!--  Product Details -->
				<div class="product product-details clearfix">
					<div class="col-md-6">
						<div id="product-main-view">
							<div class="product-view">
								<img src="{{ product.Image.url }}" alt="" style="height:400px; width:250px">
							</div>
              {% for p in images %}
							<div class="product-view">
								<img src="{{ p.Image.url }}" alt="">
							</div>
              {% endfor %}
						</div>
						<div id="product-view">
							<div class="product-view">
								<img src="{{ product.Image.url }}" alt="">
							</div>
              {% for p in images %}
              <div class="product-view">
                <img src="{{ p.Image.url }}" alt="">
              </div>
              {% endfor %}
						</div>
					</div>
					<div class="col-md-6">
						<div class="product-body">
							<div class="product-label">
								<span>New</span>
								<span class="sale">-20%</span>
							</div>
							<h2 class="product-name">{{ product.Title }}</h2>
							<h3 class="product-price">${{ product.Price }} <del class="product-old-price">$45.00</del></h3>
              <div>
                  <div class="product-rating">
                      <i class="fa fa-star{% if product.avaregereview < 1%}-o empty{% endif%}"></i>
                      <i class="fa fa-star{% if product.avaregereview < 2%}-o empty{% endif%}"></i>
                      <i class="fa fa-star{% if product.avaregereview < 3%}-o empty{% endif%}"></i>
                      <i class="fa fa-star{% if product.avaregereview < 4%}-o empty{% endif%}"></i>
                      <i class="fa fa-star{% if product.avaregereview < 5%}-o empty{% endif%}"></i>
                      {{ product.avaregereview |stringformat:".2f"}}
                  </div>
                  <a href="#tab1"> {{ product.countreview}}  Review(s) / Add Review</a>
              </div>
							<p><strong>Availability:</strong> In Stock</p>
							<p><strong>Brand:</strong> E-SHOP</p>
							<p>{{ product.Details|safe }}</p>
							<div class="product-options">
								<ul class="size-option">
									<li><span class="text-uppercase">Size:</span></li>
									<li class="active"><a href="#">S</a></li>
									<li><a href="#">XL</a></li>
									<li><a href="#">SL</a></li>
								</ul>
								<ul class="color-option">
									<li><span class="text-uppercase">Color:</span></li>
									<li class="active"><a href="#" style="background-color:#475984;"></a></li>
									<li><a href="#" style="background-color:#8A2454;"></a></li>
									<li><a href="#" style="background-color:#BF6989;"></a></li>
									<li><a href="#" style="background-color:#9A54D8;"></a></li>
								</ul>
							</div>

							<div class="product-btns">

                <form  action="/order/addtoshopcart/{{product.id}}" method="POST">
                  {% csrf_token %}
                  <div class="qty-input">
                    <span class="text-uppercase">QTY: </span>
                    <input class="input" name='Quantity' type="number" value="1" min="1" max="{{ product.Amount }}">
                  </div>
                  <button class="primary-btn add-to-cart" type="submit"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
                </form>

  								<div class="pull-right">
									<button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
									<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
									<button class="main-btn icon-btn"><i class="fa fa-share-alt"></i></button>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="product-tab">
							<ul class="tab-nav">
								<li class="active"><a data-toggle="tab" href="#tab1">Description</a></li>
								<li><a data-toggle="tab" href="#tab2">Details</a></li>
								<li><a data-toggle="tab" href="#tab3">Reviews ({{ cc }})</a></li>
							</ul>
							<div class="tab-content">
								<div id="tab1" class="tab-pane fade in active">
									<p>{{ product.Description }}</p>
								</div>
								<div id="tab2" class="tab-pane fade in">
									<div class="row">
										<div class="col-md-6">
											<div class="product-reviews">
                        {% for c in comments %}
												<div class="single-review">
													<div class="review-heading">
														<div><a href="#"><i class="fa fa-user-o"></i> {{ c.User.username }}</a></div>
                            <div><a href="#"><i class="fa fa-clock-o"></i>{{ c.Subject }}</a></div>
														<div><a href="#"><i class="fa fa-clock-o"></i>{{ c.Create_at }}</a></div>
														<div class="review-rating pull-right">                        
															<i class="fa fa-star{% if c.Rating < 1 %}-o empty{% endif %}"></i>
															<i class="fa fa-star{% if c.Rating < 2 %}-o empty{% endif %}"></i>
															<i class="fa fa-star{% if c.Rating < 3 %}-o empty{% endif %}"></i>
															<i class="fa fa-star{% if c.Rating < 4 %}-o empty{% endif %}"></i>
															<i class="fa fa-star{% if c.Rating < 5 %}-o empty{% endif %}"></i>
														</div>
													</div>
													<div class="review-body">
														<p>{{ c.Comment }}.</p>
													</div>
												</div>
                        {% endfor %}


												<ul class="reviews-pages">
													<li class="active">1</li>
													<li><a href="#">2</a></li>
													<li><a href="#">3</a></li>
													<li><a href="#"><i class="fa fa-caret-right"></i></a></li>
												</ul>
											</div>
										</div>
										<div class="col-md-6">
                      {% if messages %}
                      {% for message in messages %}
                      <div class=" alert alert-success">
                        {{ message }}
                      </div>
                      {% endfor %}
                      {% endif %}
											<h4 class="text-uppercase">Write Your Review</h4>
											<form class="review-form" action="/product/comment/{{product.id}}/" method="POST">
                      <!--  <form class="review-form" action="{% url 'Product:comment' id=product.id %}" method="POST"> -->
                        {% csrf_token %}
												<div class="form-group">
													<input name="Subject" class="input" type="text" placeholder="Subject" />
												</div>
												<div class="form-group">
													<textarea name="Comment" class="input" placeholder="Your review"></textarea>
												</div>
												<div class="form-group">
													<div class="input-rating">
														<strong class="text-uppercase">Your Rating: </strong>
														<div class="stars">
															<input type="radio" id="star5" name="Rating" value="5" /><label for="star5"></label>
															<input type="radio" id="star4" name="Rating" value="4" /><label for="star4"></label>
															<input type="radio" id="star3" name="Rating" value="3" /><label for="star3"></label>
															<input type="radio" id="star2" name="Rating" value="2" /><label for="star2"></label>
															<input type="radio" id="star1" name="Rating" value="1" /><label for="star1"></label>
														</div>
													</div>
												</div>
                        {% if user.id is not none %}
												<button class="primary-btn" type="submit">Submit</button>
                        {% else %}
                        <p>You must have to login for set your review</p>
                        {% endif %}
											</form>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>

				</div>
				<!-- /Product Details -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

 {% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

home/templates/slider.html
{% load static %}
<!-- HOME -->
	<div id="home">
		<!-- container -->
		<div class="container">
			<!-- home wrap -->
			<div class="home-wrap">
				<!-- home slick -->
				<div id="home-slick">

					<!-- banner -->
					{% for ps in products_slider %}
					<div class="banner banner-1">
						<img src="{{ ps.Image.url }}" alt="" style="height:500px">
						<div class="banner-caption text-center">
							<h1>{{ ps.Title }}</h1>
							<h3 class="white-color font-weak">{{ rp.Price }}</h3>
							<a href="/product/{{ps.id}}/{{ps.Slug}}" class="primary-btn">Shop Now</a>
						</div>
					</div>
					{% endfor %}
					<!-- /banner -->

				</div>
				<!-- /home slick -->
			</div>
			<!-- /home wrap -->
		</div>
		<!-- /container -->
	</div>
	<!-- /HOME -->