home/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from home import views
from order import views as orderviews

urlpatterns = [
    path('admin/', admin.site.urls),


    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('user/', include('user.urls')),


    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contactus, name='contactus'),
    path('category/<int:id>/<slug:slug>/', views.category_product, name='category_product'),
    path('search/', views.search, name='search_product'),
    path('product/<int:id>/<slug:slug>', views.product_details, name='product_details'),
    path('order/', orderviews.shopcart, name='shopcart' ),
    path('faq/', views.faq, name='faq')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path, include
from . import views
#from product import views

app_name='Order'

urlpatterns = [
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deleteformshopcart/<int:id>', views.deleteformshopcart, name='deleteformshopcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

order/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import Product
from django import forms

# Create your models here.
class ShopCart(models.Model):
    User = models.ForeignKey(User,on_delete=models.CASCADE)
    Product = models.ForeignKey(Product,on_delete=models.CASCADE)
    Quantity = models.IntegerField()

    def __str__(self):
        return self.Product.Title


    @property
    def price(self):
        return (self.Product.Price)

    @property
    def amount(self):
        return (self.Quantity*self.Product.Price)

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    User = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    Code = models.CharField(max_length=5, editable=False )
    First_name = models.CharField(max_length=10)
    Last_name = models.CharField(max_length=10)
    Phone = models.CharField(blank=True, max_length=20)
    Address = models.CharField(blank=True, max_length=150)
    City = models.CharField(blank=True, max_length=20)
    Country = models.CharField(blank=True, max_length=20)
    Total = models.FloatField()
    Status=models.CharField(max_length=10,choices=STATUS,default='New')
    Ip = models.CharField(blank=True, max_length=20)
    Adminnote = models.CharField(blank=True, max_length=100)
    Create_at=models.DateTimeField(auto_now_add=True)
    Update_at=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.User.first_name

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['First_name','Last_name','Address','Phone','City','Country']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    Order = models.ForeignKey(Order, on_delete=models.CASCADE)
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    #variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    Quantity = models.IntegerField()
    Price = models.FloatField()
    Amount = models.FloatField()
    Status = models.CharField(max_length=10, choices=STATUS, default='New')
    Create_at = models.DateTimeField(auto_now_add=True)
    Update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.Product.Title

order/forms.py
from django import forms
from order.models import ShopCart


class ShopCartForm(forms.ModelForm):
    class Meta:
        model = ShopCart
        fields = ['Quantity',]

user/forms.py
from django import forms
from django.forms import TextInput, EmailInput, Select, FileInput
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from user.models import UserProfile

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=25)
    password = forms.CharField(max_length=25)


class SignUpForm(UserCreationForm):
    username = forms.CharField(required=True, label="",
        widget=forms.TextInput(attrs={'placeholder':'Username'}))

    first_name = forms.CharField(required=True, label="",
        widget=forms.TextInput(attrs={'placeholder':'First name'}))

    last_name = forms.CharField(required=True, label="",
        widget=forms.TextInput(attrs={'placeholder':'Last name'}))

    email = forms.EmailField(required=True, label="",
        widget=forms.TextInput(attrs={'placeholder':'Email'}))

    password1 = forms.CharField(
            required = True,
            label = "",
            widget = forms.PasswordInput(attrs={'placeholder':'Password'})
        )

    password2 = forms.CharField(
            required = True,
            label = "",
            widget = forms.PasswordInput(attrs={'placeholder':'Confirm Password'})
        )
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2',]



class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ( 'username','email','first_name','last_name')
        widgets = {
            'username'  : TextInput(attrs={'class': 'input','placeholder':'Username'}),
            'email'     : EmailInput(attrs={'class': 'input','placeholder':'Email'}),
            'first_name': TextInput(attrs={'class': 'input','placeholder':'First_name'}),
            'last_name' : TextInput(attrs={'class': 'input','placeholder':'Last_name' }),
        }

CITY = [
    ('Dhaka', 'Dhaka'),
    ('Rajshahi', 'Rajshahi'),
    ('Rangpur', 'Rangpur'),
    ]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('Phone', 'Address', 'City','Country','Image',)
        widgets = {
            'Phone'     : TextInput(attrs={'class': 'input','placeholder':'phone'}),
            'Address'   : TextInput(attrs={'class': 'input','placeholder':'address'}),
            'City'      : Select(attrs={'class': 'input','placeholder':'city'},choices=CITY),
            'Country'   : TextInput(attrs={'class': 'input','placeholder':'country' }),
            'Image'     : FileInput(attrs={'class': 'input', 'placeholder': 'image', }),
        }

order/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from order.models import ShopCart
from order.forms import ShopCartForm
from order.models import Order, OrderForm, OrderProduct
from product.models import Category, Product
from home.models import Setting
from user.models import UserProfile

from django.db.models import Avg, Max, Min, Sum
from django.utils.crypto import get_random_string


@login_required(login_url='/user/login/') # Check login
def addtoshopcart(request,id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user
    checkproduct = ShopCart.objects.filter(Product_id=id, User_id=current_user.id)

    if checkproduct:
        control = 1
    else:
        control = 0

    if request.method=='POST':
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control==1:
                data = ShopCart.objects.get(Product_id=id, User_id=current_user.id)
                data.Quantity += form.cleaned_data['Quantity']
                data.save()
            else:
                data = ShopCart()
                data.User_id = current_user.id
                data.Product_id = id
                data.Quantity = form.cleaned_data['Quantity']
                data.save()
        messages.success(request,'Product Added to Shop Cart')

    else:
        if control==1:
            data = ShopCart.objects.get(Product_id=id, User_id=current_user.id)
            data.Quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.User_id = current_user.id
            data.Product_id = id
            data.Quantity = 1
            data.save()
        messages.success(request,'Product Added to Shop Cart')

    return HttpResponseRedirect(url)

def shopcart(request):
    category = Category.objects.all()
    setting = Setting.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(User_id=current_user.id)
    orderqty = ShopCart.objects.filter(User_id=current_user.id).aggregate(Sum('Quantity'))
    orderqty = orderqty['Quantity__sum']

    total = 0
    for sctotal in shopcart:
        total += sctotal.Quantity * sctotal.Product.Price

    context ={
        'category':category,
        'setting':setting,
        'shopcart':shopcart,
        'orderqty':orderqty,
        'total':total,
    }
    return render(request,'ShopCart_Products.html', context)

@login_required(login_url='/user/login/') # Check login
def deleteformshopcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request,'Remove From Shop Cart')
    return HttpResponseRedirect('/order/')


def orderproduct(request):
    #form = OrderForm()
    category = Category.objects.all()
    setting = Setting.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(User_id=current_user.id)
    shopcart = ShopCart.objects.filter(User_id=current_user.id)
    orderqty = ShopCart.objects.filter(User_id=current_user.id).aggregate(Sum('Quantity'))
    orderqty = orderqty['Quantity__sum']
    #print(orderqty)

    total = 0
    for sctotal in shopcart:
        total += sctotal.Quantity * sctotal.Product.Price
        #print(total)

    if request.method=='POST':
        form = OrderForm(request.POST)
        #print(form)
        #print(request.POST['First_name'])
        if form.is_valid():
            data = Order()
            data.First_name=form.cleaned_data['First_name']
            data.Last_name=form.cleaned_data['Last_name']
            data.City=form.cleaned_data['City']
            data.Country=form.cleaned_data['Country']
            data.Phone=form.cleaned_data['Phone']
            data.Address=form.cleaned_data['Address']
            data.User_id=current_user.id
            data.Total=total
            data.Ip=request.META.get('REMOTE_ADDR')
            ordercode=get_random_string(5).upper()
            data.Code=ordercode
            #print(ordercode)
            data.save()

            shopcart = ShopCart.objects.filter(User_id=current_user.id)
            for sc in shopcart:
                orderdetails=OrderProduct()
                orderdetails.Order_id = data.id
                orderdetails.User_id = current_user.id
                orderdetails.Product_id = sc.Product_id
                #print(orderdetails.Product_id)
                orderdetails.Quantity = sc.Quantity
                orderdetails.Price = sc.Product.Price
                #orderdetails.Price = sc.price
                orderdetails.Amount = sc.amount
                #orderdetails.Amount = sc.Product.Price * sc.Quantity
                orderdetails.save()

                #Quantity Deduction From Stock
                product = Product.objects.get(id=sc.Product_id)
                product.Amount -= sc.Quantity
                product.save()

            shopcart = ShopCart.objects.filter(User_id=current_user.id).delete()
            request.session['cart_items']=0
            messages.success(request,'Your order is completed successfully')
            context={
                'ordercode':ordercode,
                'category':category,
                'setting':setting,
            }
            return render(request,'order_complete.html',context)

        else:
            #Need to code another system here. This only for test basis
            print('Form is not valid')
    else:
        #Need to code another system here. This only for test basis
        print('Form is not posted')

    context ={
        'category':category,
        'setting':setting,
        'shopcart':shopcart,
        'orderqty':orderqty,
        'total':total,
        'profile':profile,
    }
    return render(request,'order_form.html', context)

order/templates/ShopCart_Products.html
{% extends 'homebase.html' %}
{% block title %} Shop Cart {% endblock %}
{% block description %} {{ setting.keywords }} {% endblock %}
{% block keywords %} {{ setting.Description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="/">Home</a></li>
      <li class="active">Shop Cart </li>
    </ul>
  </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">

      <div class="col-md-12">
        <div class="order-summary clearfix">
          <div class="section-title">
            <h3 class="title">Order Review</h3>
          </div>
          <table class="shopping-cart-table table">
            <thead>
              <tr>
                <th>Product</th>
                <th></th>
                <th class="text-center">Price</th>
                <th class="text-center">Quantity</th>
                <th class="text-center">Total</th>
                <th class="text-right"></th>
              </tr>
            </thead>
            <tbody>
              {% for sc in shopcart %}
              <tr>
                <td class="thumb"><img src="{{sc.Product.Image.url}}" alt=""></td>
                <td class="details">
                  <a href="/product/{{sc.Product_id}}/{{sc.Product.Slug}} ">{{sc.Product.Title}}</a>
                  <ul>
                    <li><span>Size: XL</span></li>
                    <li><span>Color: Camelot</span></li>
                  </ul>
                </td>
                <td class="price text-center"><strong>${{sc.price}}.50</strong><br></td>
                <td class="qty text-center"><input class="input" type="number" value="{{sc.Quantity}}"></td>
                <td class="total text-center"><strong class="primary-color">${{sc.amount}}</strong></td>
                <td class="text-right"><a href="/order/deleteformshopcart/{{sc.id}}"><button class="main-btn icon-btn"><i class="fa fa-close"></i></button></a></td>
              </tr>
              {% endfor %}

            </tbody>
            <tfoot>
              <tr>
                <th class="empty" colspan="3"></th>
                <th>SUBTOTAL</th>
                <th colspan="2" class="sub-total">${{total}}</th>
              </tr>
              <tr>
                <th class="empty" colspan="3"></th>
                <th>SHIPING</th>
                <td colspan="2">Free Shipping</td>
              </tr>
              <tr>
                <th class="empty" colspan="3"></th>
                <th>TOTAL</th>
                <th colspan="2" class="total">${{total}}</th>
              </tr>
            </tfoot>
          </table>
          <div class="pull-right">
            <a href="/order/orderproduct/"><button class="primary-btn">Place Order</button></a>
          </div>
        </div>

      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /section -->

{% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

order/templates/order_complete.html
{% extends 'homebase.html' %}

{% block title %} Order Complated {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

    <!-- BREADCRUMB -->
    <div id="breadcrumb">
        <div class="container">
            <ul class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Order Complated</li>
            </ul>
        </div>
    </div>
    <!-- /BREADCRUMB -->
    <!-- section -->
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <div class="col-md-12">
                    <div class="order-summary clearfix">
                        <div class="section-title">
                            <h3 class="title">Order Complated</h3>
                        </div>
                        <hr>
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Order Code : {{ ordercode }}</h3>
                        <h3>Thank You</h3>
                        <hr>

                    </div>

                </div>


            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

{% endblock %}

order/templates/order_form.html
{% extends 'homebase.html' %}
{% block title %} Order  {% endblock %}
{% block description %} {{ setting.keywords }} {% endblock %}
{% block keywords %} {{ setting.Description }} {% endblock %}
{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}
{% block body %}
<!-- BREADCRUMB -->
<div id="breadcrumb">
   <div class="container">
      <ul class="breadcrumb">
         <li><a href="/">Home</a></li>
         <li class="active">Order Place</li>
      </ul>
   </div>
</div>
<!-- /BREADCRUMB -->
<!-- section -->
<div class="section">
   <!-- container -->
   <div class="container">
      <!-- row -->
      <div class="row">
         <Form action="/order/orderproduct/" method="POST">
            {% csrf_token %}
            <div class="col-md-6">
               <div class="billing-details">
                  <div class="section-title">
                     <h4 class="title">Shipping Details</h4>
                  </div>
                  <p><label for="id_first_name">First name:</label>
                     <input type="text" name="First_name"  value="{{ user.first_name }}" class="input" maxlength="20" required id="id_first_name">
                  </p>
                  <p><label for="id_last_name">Last name:</label>
                     <input type="text" name="Last_name"  value="{{ user.last_name }}" class="input" maxlength="20" required id="id_last_name">
                  </p>
                  <p><label for="id_address">Address:</label>
                     <input type="text" name="Address" value="{{ profile.Address }}" class="input" maxlength="150" id="id_address">
                  </p>
                  <p><label for="id_phone">Phone:</label>
                     <input type="text" name="Phone"  value="{{ profile.Phone }}"  class="input" maxlength="20" id="id_phone">
                  </p>
                  <p>
                     <label for="id_city">City:</label>
                     <select name="City" class="input" id="id_city">
                        <option value="{{ profile.city }}" selected>{{ profile.City }}</option>
                        <option value="Dhaka">Dhaka</option>
                        <option value="Rajshahi">Rajshahi</option>
                        <option value="Bogura">Bogura</option>
                        <option value="Sirajgonj">Sirajgonj</option>
                        <option value="Khula">Khula</option>
                        <option value="Rajbari">Rajbari</option>
                     </select>
                  </p>
                  <p><label for="id_first_name">Country:</label>
                     <input type="text" name="Country" class="input" id="id_country" value="{{ profile.Country }}">
                  </p>
                  <div class="pull-right">
                     <button  type="submit" class="primary-btn">Complete Order</button>
                  </div>
               </div>
            </div>
            <div class="col-md-6">
               <div class="shiping-methods">
                  <div class="section-title">
                     <h4 class="title">Payment Information</h4>
                  </div>
                  <p><label for="id_first_name">Total: </label>
                     <input type="text" name="total" class="input" readonly value="${{ total }}">
                  </p>
                  <p><label for="id_first_name">Credit Card Holder</label>
                     <input type="text" name="holder" class="input"  value="">
                  </p>
                  <p><label for="id_first_name">Credit Card Number</label>
                     <input type="text" name="number" class="input"  value="">
                  </p>
                  <p><label for="id_first_name">Credit Exp Date/Year</label>
                     <input type="text" name="ecpdate" class="input"  placeholder="mm/yy">
                  </p>
                  <p><label for="id_first_name">Security Number</label>
                     <input type="text" name="secnumber" class="input"  value="">
                  </p>
               </div>
            </div>
         </Form>
         <div class="col-md-12">
            <div class="order-summary clearfix">
               <div class="section-title">
                  <h3 class="title">Order Review</h3>
               </div>
               <table class="shopping-cart-table table">
                  <thead>
                     <tr>
                        <th>Product</th>
                        <th></th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                        <th class="text-center">Total</th>
                        <th class="text-right"></th>
                     </tr>
                  </thead>
                  <tbody>
                     {% for sc in shopcart %}
                     <tr>
                        <td class="thumb"><img src="{{sc.Product.Image.url}}" alt=""></td>
                        <td class="details">
                           <a href="/product/{{sc.Product_id}}/{{sc.Product.Slug}} ">{{sc.Product.Title}}</a>
                           <ul>
                              <li><span>Size: XL</span></li>
                              <li><span>Color: Camelot</span></li>
                           </ul>
                        </td>
                        <td class="price text-center"><strong>${{sc.price}}.50</strong><br></td>
                        <td class="qty text-center"><input class="input" type="number" value="{{sc.Quantity}}"></td>
                        <td class="total text-center"><strong class="primary-color">${{sc.amount}}</strong></td>
                        <td class="text-right"><a href="/order/deleteformshopcart/{{sc.id}}"><button class="main-btn icon-btn"><i class="fa fa-close"></i></button></a></td>
                     </tr>
                     {% endfor %}
                  </tbody>
                  <tfoot>
                     <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SUBTOTAL</th>
                        <th colspan="2" class="sub-total">${{total}}</th>
                     </tr>
                     <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SHIPING</th>
                        <td colspan="2">Free Shipping</td>
                     </tr>
                     <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL</th>
                        <th colspan="2" class="total">${{total}}</th>
                     </tr>
                  </tfoot>
               </table>
               <div class="pull-right">
               </div>
            </div>
         </div>
      </div>
      <!-- /row -->
   </div>
   <!-- /container -->
</div>
<!-- /section -->
{% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}